"""`atm completion bash|zsh|fish`：从 argparse 的定义**生成**补全脚本，不手写第二份命令表。

手写补全脚本的下场都一样：加了子命令忘了改，半年后补全和实际对不上。这里直接遍历
`_build_parser()` 产出的子命令、每个子命令的选项、以及几个有限枚举（配置键、来源名、程序名），
所以补全永远和 `--help` 一致。

用法（写进 shell rc）：
    eval "$(atm completion bash)"          # bash
    eval "$(atm completion zsh)"           # zsh（需要 compinit 已加载）
    atm completion fish | source           # fish；或存到 ~/.config/fish/completions/atm.fish
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass

from .i18n import _


@dataclass(frozen=True, slots=True)
class CommandSpec:
    name: str
    help: str
    options: tuple[str, ...]


def collect(parser: argparse.ArgumentParser) -> tuple[tuple[str, ...], list[CommandSpec]]:
    """(顶层选项, 子命令列表)。只认长短选项，位置参数不进补全表。"""
    top = tuple(_options_of(parser))
    specs: list[CommandSpec] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {a.dest: a.help or "" for a in action._choices_actions}
            for name, sub in action.choices.items():
                specs.append(CommandSpec(name, helps.get(name, ""), tuple(_options_of(sub))))
    return top, specs


def _options_of(parser: argparse.ArgumentParser) -> list[str]:
    out: list[str] = []
    for action in parser._actions:
        if action.help == argparse.SUPPRESS:
            continue
        out.extend(s for s in action.option_strings if s.startswith("-"))
    return out


def render(
    shell: str,
    parser: argparse.ArgumentParser,
    *,
    config_keys: tuple[str, ...],
    sources: tuple[str, ...],
) -> str:
    top, specs = collect(parser)
    if shell == "bash":
        return _bash(top, specs, config_keys, sources)
    if shell == "zsh":
        return _zsh(top, specs, config_keys, sources)
    if shell == "fish":
        return _fish(top, specs, config_keys, sources)
    raise ValueError(_("不支持的 shell {shell!r}，可选 bash / zsh / fish").format(shell=shell))


def _bash(top, specs, config_keys, sources) -> str:
    cases = "\n".join(f'        {s.name}) opts="{" ".join(s.options)}" ;;' for s in specs)
    return f"""# atm bash completion — generated by `atm completion bash`
_atm() {{
    local cur prev cmd opts
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    cmd="${{COMP_WORDS[1]}}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "{" ".join(s.name for s in specs)} {" ".join(top)}" -- "$cur") )
        return 0
    fi
    case "$prev" in
        --source) COMPREPLY=( $(compgen -W "{" ".join(sources)}" -- "$cur") ); return 0 ;;
    esac
    if [[ "$cmd" == config && $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "{" ".join(config_keys)} --unset --reset --path --json" \\
            -- "$cur") )
        return 0
    fi
    if [[ "$cmd" == completion && $COMP_CWORD -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ); return 0
    fi
    case "$cmd" in
{cases}
        *) opts="" ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    return 0
}}
complete -F _atm atm
"""


def _zsh(top, specs, config_keys, sources) -> str:
    cmd_lines = "\n".join(f"        '{s.name}:{_zq(s.help)}'" for s in specs)
    cases = "\n".join(
        f"        {s.name}) _arguments {' '.join(_zopt(o) for o in s.options)} '*:arg:_files' ;;"
        for s in specs
    )
    return f"""#compdef atm
# atm zsh completion — generated by `atm completion zsh`
_atm() {{
    local -a cmds
    cmds=(
{cmd_lines}
    )
    if (( CURRENT == 2 )); then
        _describe 'atm command' cmds
        return
    fi
    case "$words[2]" in
        config)
            if (( CURRENT == 3 )); then
                _values 'config key' {" ".join(config_keys)} --unset --reset --path --json
                return
            fi ;;
        completion)
            (( CURRENT == 3 )) && _values 'shell' bash zsh fish && return ;;
    esac
    if [[ "$words[CURRENT-1]" == --source ]]; then
        _values 'source' {" ".join(sources)}
        return
    fi
    case "$words[2]" in
{cases}
    esac
}}
compdef _atm atm
"""


def _fish(top, specs, config_keys, sources) -> str:
    lines = ["# atm fish completion — generated by `atm completion fish`", "complete -c atm -f"]
    for s in specs:
        lines.append(f"complete -c atm -n '__fish_use_subcommand' -a {s.name} -d '{_fq(s.help)}'")
        for opt in s.options:
            if opt.startswith("--"):
                lines.append(
                    f"complete -c atm -n '__fish_seen_subcommand_from {s.name}' -l {opt[2:]}"
                )
            elif len(opt) == 2:
                lines.append(
                    f"complete -c atm -n '__fish_seen_subcommand_from {s.name}' -s {opt[1:]}"
                )
    lines.append(
        f"complete -c atm -n '__fish_seen_subcommand_from config' -a '{' '.join(config_keys)}'"
    )
    lines.append("complete -c atm -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'")
    lines.append(
        "complete -c atm -n '__fish_seen_subcommand_from list pick' -l source -x "
        f"-a '{' '.join(sources)}'"
    )
    return "\n".join(lines) + "\n"


def _zopt(opt: str) -> str:
    return f"'{opt}[{opt}]'"


def _zq(text: str) -> str:
    return text.replace("'", "'\\''").replace(":", "\\:")


def _fq(text: str) -> str:
    return text.replace("'", "\\'")
