"""tmux 输出解析 + 文本处理。

`parse_panes` 是纯函数，专门拆出来测 —— tmux 换版本改了输出格式的话，这里会第一个红。
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

from atm import tmux
from atm.fuzzy import rank, score
from atm.model import SessionEntry, Source
from atm.text import (
    clean_title,
    display_width,
    humanize_age,
    is_junk_prompt,
    pad_display,
    truncate_display,
)

SEP = "\x1f"


def _pane_line(**overrides: object) -> str:
    fields = {
        "id": "%1",
        "session": "main",
        "window_index": "0",
        "window_name": "zsh",
        "pane_index": "0",
        "command": "bash",
        "path": "/home/sean",
        "active": "1",
        "in_mode": "0",
        "window_active": "1",
        "width": "80",
        "height": "24",
        "title": "sean@host",
    }
    fields.update({k: str(v) for k, v in overrides.items()})
    return SEP.join(str(v) for v in fields.values())


# ---------------------------------------------------------------- tmux


def test_parse_panes_basic() -> None:
    panes = tmux.parse_panes(_pane_line() + "\n" + _pane_line(id="%2", command="claude"))
    assert len(panes) == 2
    assert panes[0].id == "%1"
    assert panes[0].is_idle_shell is True
    assert panes[1].is_idle_shell is False
    assert panes[0].label == "main:0.0"


def test_parse_panes_handles_paths_with_pipes_and_spaces() -> None:
    """用 \\x1f 当分隔符就是为了这个 —— 路径里有 | 和空格也不能串列。"""
    panes = tmux.parse_panes(_pane_line(path="/home/sean/a b|c", title="a|b"))
    assert panes[0].current_path == "/home/sean/a b|c"
    assert panes[0].title == "a|b"


def test_pane_in_copy_mode_is_not_idle() -> None:
    """pane 滚进 copy-mode 后前台仍是 bash，但 send-keys 会被当导航键吃掉。"""
    normal = tmux.parse_panes(_pane_line(in_mode="0"))[0]
    scrolled = tmux.parse_panes(_pane_line(in_mode="1"))[0]
    assert normal.is_idle_shell is True
    assert scrolled.current_command == "bash"
    assert scrolled.is_idle_shell is False, "copy-mode 的 pane 不该被判为可投递"


def test_more_posix_shells_recognised() -> None:
    """白名单漏了会把空闲 pane 误判成忙碌而拒绝投递。"""
    for sh in ("rbash", "mksh", "yash", "dash", "ash", "fish"):
        assert tmux.parse_panes(_pane_line(command=sh))[0].is_idle_shell, sh


def test_non_posix_shells_are_not_dispatch_targets() -> None:
    """是 shell，但我们生成的是 POSIX 语法 —— 投进去会执行成别的东西，默认要拦。"""
    for sh in ("pwsh", "powershell", "csh", "tcsh", "nu", "elvish", "xonsh", "osh", "rc"):
        pane = tmux.parse_panes(_pane_line(command=sh))[0]
        assert pane.is_idle_shell is False, sh
        assert pane.is_non_posix_shell is True, sh


def test_non_posix_refusal_explains_why() -> None:
    """拒绝理由要说清是「语法不兼容」而不是「pane 忙」—— 否则用户会以为等一下就好。"""
    from atm.dispatch import busy_reason

    pane = tmux.parse_panes(_pane_line(command="nu"))[0]
    assert "POSIX" in busy_reason(pane)


def test_parse_panes_skips_malformed_lines() -> None:
    """格式对不上就跳过那一行，不能让整个列表挂掉。"""
    panes = tmux.parse_panes("garbage\n" + _pane_line() + "\ntoo" + SEP + "few")
    assert len(panes) == 1


def test_parse_panes_skips_non_numeric_fields() -> None:
    panes = tmux.parse_panes(_pane_line(width="not-a-number"))
    assert panes == ()


def test_parse_panes_empty() -> None:
    assert tmux.parse_panes("") == ()
    assert tmux.parse_panes("\n\n") == ()


# ---------------------------------------------------------------- text


def test_is_junk_prompt_catches_injected_wrappers() -> None:
    assert is_junk_prompt("<local-command-caveat>x</local-command-caveat>") is True
    assert is_junk_prompt("<command-name>/effort</command-name>") is True
    assert is_junk_prompt("<system-reminder>x</system-reminder>") is True
    assert is_junk_prompt("Caveat: The messages below were generated by the user") is True
    assert is_junk_prompt("   ") is True
    assert is_junk_prompt("正常的一句话") is False


def test_clean_title_collapses_and_strips_markdown() -> None:
    assert clean_title("# 项目背景\n\n  第二行  ") == "项目背景 第二行"


def test_display_width_counts_cjk_as_two() -> None:
    assert display_width("abc") == 3
    assert display_width("中文") == 4
    assert display_width("a中") == 3


def test_truncate_display_respects_cjk_width() -> None:
    """按显示宽度截断，中文标题不能把列表撑歪。"""
    assert display_width(truncate_display("中文中文中文", 6)) <= 6
    assert truncate_display("abcdef", 10) == "abcdef"
    assert truncate_display("abcdef", 4).endswith("…")


def test_pad_display_pads_to_width() -> None:
    assert display_width(pad_display("中", 6)) == 6
    assert display_width(pad_display("abcdefgh", 4)) == 4


def test_humanize_age_buckets() -> None:
    assert humanize_age(10) == "now"
    assert humanize_age(300) == "5m"
    assert humanize_age(7200) == "2h"
    assert humanize_age(86400 * 3) == "3d"
    assert humanize_age(86400 * 14) == "2w"


# ---------------------------------------------------------------- fuzzy


def test_score_subsequence_match() -> None:
    assert score("abc", "aXbXc") is not None
    assert score("abc", "acb") is None


def test_score_prefers_consecutive_and_word_start() -> None:
    consecutive = score("cache", "cache layer")
    scattered = score("cache", "c a c h e")
    assert consecutive is not None and scattered is not None
    assert consecutive.score > scattered.score


def test_smart_case() -> None:
    assert score("abc", "ABC") is not None  # 全小写查询 → 不敏感
    assert score("ABC", "abc") is None  # 有大写 → 敏感


def test_empty_query_matches_everything() -> None:
    match = score("", "anything")
    assert match is not None and match.positions == ()


def _entry(title: str, days_ago: int = 0) -> SessionEntry:
    return SessionEntry(
        id=title,
        title=title,
        source=Source.CLAUDE,
        cwd="/home/sean/demo",
        git_branch=None,
        updated_at=datetime.now(tz=UTC) - timedelta(days=days_ago),
        path=f"/tmp/{title}.jsonl",
        size_bytes=1,
    )


def test_rank_keeps_original_order_for_empty_query() -> None:
    entries = [_entry("b"), _entry("a")]
    assert [s.entry.title for s in rank(entries, "")] == ["b", "a"]


def test_rank_filters_and_sorts() -> None:
    entries = [_entry("缓存层"), _entry("cache layer"), _entry("无关")]
    result = rank(entries, "cache")
    assert [s.entry.title for s in result] == ["cache layer"]


def test_rank_breaks_ties_by_recency() -> None:
    entries = [_entry("cache", days_ago=10), _entry("cache", days_ago=1)]
    result = rank(entries, "cache")
    assert result[0].entry.updated_at > result[1].entry.updated_at


def test_haystack_includes_cwd_and_source() -> None:
    entry = _entry("标题")
    assert rank([entry], "demo")
    assert rank([entry], "claude")


# ------------------------------------------------- 注入包装剥离（实测回归）


def test_strip_wrapper_blocks_removes_leading_injected_xml() -> None:
    """Codex 0.147 会在真实提问前塞 <recommended_plugins>…</environment_context>。"""
    from atm.text import strip_wrapper_blocks

    raw = "<recommended_plugins>\n- Airtable\n</recommended_plugins>\n\n真正的问题是什么"
    assert strip_wrapper_blocks(raw) == "真正的问题是什么"


def test_strip_wrapper_blocks_handles_multiple_blocks() -> None:
    from atm.text import strip_wrapper_blocks

    raw = "<a>x</a>\n<b attr='1'>y</b>\n实际内容"
    assert strip_wrapper_blocks(raw) == "实际内容"


def test_known_wrapper_without_closing_tag_is_still_junk() -> None:
    """已知的注入包装即使没闭合也算噪音 —— 靠标签名单挡，不靠「没闭合」这个特征。"""
    assert is_junk_prompt("<environment_context>no closing tag here") is True


def test_unknown_unclosed_tag_is_NOT_discarded() -> None:
    """以尖括号 token 开头的**正常提问**不能被整条丢掉。

    之前 strip_wrapper_blocks 见到没闭合的开头标签就 return ""，
    于是 `<div class="x"> 这个标签为什么…` 这类真实提问整条被判成噪音、从列表消失。
    """
    from atm.text import strip_wrapper_blocks

    real = '<div class="box"> 这个标签为什么不居中？'
    assert strip_wrapper_blocks(real) == real
    assert is_junk_prompt(real) is False
    assert "这个标签为什么不居中" in clean_title(real)


def test_wrapper_only_message_is_junk() -> None:
    assert is_junk_prompt("<recommended_plugins>only wrapper</recommended_plugins>") is True


def test_clean_title_uses_content_after_wrapper() -> None:
    assert clean_title("<foo>noise</foo>\n\n# 真标题\n第二行") == "真标题 第二行"


def test_angle_brackets_inside_body_are_untouched() -> None:
    """用户正文里的尖括号不该被当包装剥掉。"""
    assert clean_title("比较 a < b > c 的写法") == "比较 a < b > c 的写法"


def test_humanize_age_ago_matches_claude_code_format() -> None:
    """格式取自 claude 二进制里 strings 出来的 UI 文案。"""
    from atm.text import humanize_age_ago

    assert humanize_age_ago(10) == "just now"
    assert humanize_age_ago(300) == "5m ago"
    assert humanize_age_ago(7200) == "2h ago"
    assert humanize_age_ago(86400 * 3) == "3d ago"


# ------------------------------------------------- 宽度计算与截断（实测回归）


def test_zero_width_chars_count_as_zero_columns() -> None:
    """ZWJ / VS16 / 零宽空格 / 肤色修饰符都不占列。

    `unicodedata.combining()` 对它们全返回 0，拦不住 —— 实测
    display_width('👨‍👩‍👧‍👦') 曾算出 11 列（终端实际渲染 2 列），
    导致标题提前截断、pad_display 补位全错。
    """
    assert display_width("‍") == 0  # ZWJ
    assert display_width("​") == 0  # ZWSP
    assert display_width("️") == 0  # VS16
    assert display_width("‎") == 0  # LRM
    assert display_width("👨‍👩‍👧‍👦") == 8  # 4 个双宽 emoji，3 个 ZWJ 不计


def test_truncate_is_single_pass_and_bounded() -> None:
    """截断不该为了「判断超没超」把整条 60KB 消息扫完。"""
    huge = "x" * 200_000
    out = truncate_display(huge, 20)
    assert display_width(out) <= 20
    assert out.endswith("…")


def test_truncate_exact_fit_not_truncated() -> None:
    assert truncate_display("abcde", 5) == "abcde"
    assert truncate_display("中文中", 6) == "中文中"


def test_truncate_boundary_off_by_one() -> None:
    assert truncate_display("abcdef", 5).endswith("…")
    assert display_width(truncate_display("abcdef", 5)) <= 5


def test_clean_title_bounded_on_huge_input() -> None:
    """整条消息可能有 60KB，但正则只该啃有界的前缀。"""
    huge = "开头正文 " + "填充" * 40_000
    out = clean_title(huge, limit=40)
    assert display_width(out) <= 40
    assert out.startswith("开头正文")


def test_pad_display_correct_with_emoji() -> None:
    padded = pad_display("👍", 6)
    assert display_width(padded) == 6


def test_tail_display_keeps_the_end() -> None:
    """输入行截断必须保尾 —— 光标在末尾，截头才看得见正在打的字。"""
    from atm.text import display_width, tail_display

    assert tail_display("abcdefghij", 20) == "abcdefghij"
    out = tail_display("abcdefghij", 6)
    assert out.endswith("ij")
    assert display_width(out) <= 6
    assert tail_display("中文中文中文", 5).endswith("中文")
    assert display_width(tail_display("中文中文中文", 5)) <= 5
    assert tail_display("abc", 0) == ""
    assert display_width(tail_display("abcdef", 1)) <= 1


def test_heading_before_injected_block_is_stripped() -> None:
    """Codex 注入 AGENTS.md 时前面带一行 Markdown 标题，标题行挡住了包装剥离。

    实测后果：那条注入本身成了会话标题，再被噪音规则当机器调用隐藏 ——
    一条 625KB、含 4 条真人消息的会话就这么从列表里消失了。
    """
    from atm.text import strip_wrapper_blocks

    injected = (
        "# AGENTS.md instructions for /home/sean/IdeaProjects/sample-backend\n\n"
        "<INSTRUCTIONS>\n一大堆项目约定……\n</INSTRUCTIONS>"
    )
    assert strip_wrapper_blocks(injected).strip() == ""

    with_real_question = injected + "\n\n现在设置的默认模型是什么"
    assert strip_wrapper_blocks(with_real_question).strip() == "现在设置的默认模型是什么"


def test_plain_heading_is_not_stripped() -> None:
    """单独的标题行是正常内容 —— 只有紧跟着包装标签时才算注入的一部分。"""
    from atm.text import strip_wrapper_blocks

    assert strip_wrapper_blocks("# 我的笔记\n\n这段要保留").startswith("# 我的笔记")
    assert strip_wrapper_blocks("# 标题\n\n普通正文") == "# 标题\n\n普通正文"
